package:
  name: ros-noetic-dynamixel-sdk
  version: 3.7.51
source:
  git_url: https://github.com/ROBOTIS-GIT-release/DynamixelSDK-release.git
  git_rev: release/noetic/dynamixel_sdk/3.7.51-4
  folder: ros-noetic-dynamixel-sdk/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
    - ros-noetic-roscpp
    - ros-noetic-rospy
  run:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
